
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Charles Ian
 * 
 */
public class CalculatorFrame extends javax.swing.JFrame implements WindowListener{
    
    /**
     * Creates new form CalculatorFrame
     */
    public CalculatorFrame() {
        initComponents();
        CalculatorApp calc = new CalculatorApp();
        jPanel1.add(calc);
        clock();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        calcButt = new javax.swing.JButton();
        textButt = new javax.swing.JButton();
        musicButt = new javax.swing.JButton();
        alarmButt = new javax.swing.JButton();
        paintButt = new javax.swing.JButton();
        stopButt = new javax.swing.JButton();
        jLabelDate = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabelDate1 = new javax.swing.JLabel();
        jLabelTime1 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cardinal OS Group 6");
        setMinimumSize(new java.awt.Dimension(1095, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(null);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 820, 480));

        calcButt.setOpaque(false);
        calcButt.setContentAreaFilled(false);
        calcButt.setBorderPainted(false);
        calcButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Calculator_LM.png"))); // NOI18N
        calcButt.setMaximumSize(new java.awt.Dimension(140, 80));
        calcButt.setPreferredSize(new java.awt.Dimension(140, 80));
        calcButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtActionPerformed(evt);
            }
        });
        getContentPane().add(calcButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 80));

        textButt.setOpaque(false);
        textButt.setContentAreaFilled(false);
        textButt.setBorderPainted(false);
        textButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Text Editor_LM.png"))); // NOI18N
        textButt.setText("jButton2");
        textButt.setMaximumSize(new java.awt.Dimension(140, 80));
        textButt.setPreferredSize(new java.awt.Dimension(140, 80));
        textButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textButtActionPerformed(evt);
            }
        });
        getContentPane().add(textButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        musicButt.setOpaque(false);
        musicButt.setContentAreaFilled(false);
        musicButt.setBorderPainted(false);
        musicButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Music Player_LM.png"))); // NOI18N
        musicButt.setMaximumSize(new java.awt.Dimension(140, 80));
        musicButt.setPreferredSize(new java.awt.Dimension(140, 80));
        musicButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicButtActionPerformed(evt);
            }
        });
        getContentPane().add(musicButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 90));

        alarmButt.setOpaque(false);
        alarmButt.setContentAreaFilled(false);
        alarmButt.setBorderPainted(false);
        alarmButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Alarm_LM.png"))); // NOI18N
        alarmButt.setMaximumSize(new java.awt.Dimension(140, 80));
        alarmButt.setPreferredSize(new java.awt.Dimension(140, 80));
        alarmButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarmButtActionPerformed(evt);
            }
        });
        getContentPane().add(alarmButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        paintButt.setOpaque(false);
        paintButt.setContentAreaFilled(false);
        paintButt.setBorderPainted(false);
        paintButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Paint_LM.png"))); // NOI18N
        paintButt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        paintButt.setMaximumSize(new java.awt.Dimension(140, 80));
        paintButt.setMinimumSize(new java.awt.Dimension(140, 80));
        paintButt.setPreferredSize(new java.awt.Dimension(140, 80));
        paintButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintButtActionPerformed(evt);
            }
        });
        getContentPane().add(paintButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        stopButt.setOpaque(false);
        stopButt.setContentAreaFilled(false);
        stopButt.setBorderPainted(false);
        stopButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Stopwatch_LM.png"))); // NOI18N
        stopButt.setMaximumSize(new java.awt.Dimension(140, 80));
        stopButt.setMinimumSize(new java.awt.Dimension(140, 80));
        stopButt.setPreferredSize(new java.awt.Dimension(140, 80));
        stopButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtActionPerformed(evt);
            }
        });
        getContentPane().add(stopButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));
        getContentPane().add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 30, 280, 40));
        getContentPane().add(jLabelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 290, 40));
        getContentPane().add(jLabelDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 330, 40));
        getContentPane().add(jLabelTime1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 320, 50));

        home.setOpaque(false);
        home.setContentAreaFilled(false);
        home.setBorderPainted(false);
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/HomeButton_LM.png"))); // NOI18N
        home.setText("home");
        home.setMaximumSize(new java.awt.Dimension(140, 80));
        home.setPreferredSize(new java.awt.Dimension(140, 80));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/Calculator__LM.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(1080, 722));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musicButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicButtActionPerformed
        // TODO add your handling code here:
        MusicFrame msc = new MusicFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                msc.setVisible(true);
                CalculatorFrame.this.setVisible(false);
                CalculatorFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_musicButtActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main.setVisible(true);
                CalculatorFrame.this.setVisible(false);
                CalculatorFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_homeActionPerformed

    private void calcButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtActionPerformed
        // TODO add your handling code here:
        CalculatorFrame cal = new CalculatorFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cal.setVisible(true);
                CalculatorFrame.this.setVisible(false);
                CalculatorFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_calcButtActionPerformed

    private void textButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textButtActionPerformed
        // TODO add your handling code here:
        textEditorFrame txtEd = new textEditorFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                txtEd.setVisible(true);
                CalculatorFrame.this.setVisible(false);
                CalculatorFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_textButtActionPerformed

    private void alarmButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarmButtActionPerformed
        // TODO add your handling code here:
        Alarm alrm = new Alarm();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                alrm.setVisible(true);
                CalculatorFrame.this.setVisible(false);
                CalculatorFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_alarmButtActionPerformed

    private void paintButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintButtActionPerformed
        // TODO add your handling code here:
        PaintFrame pnt = new PaintFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pnt.setVisible(true);
                CalculatorFrame.this.setVisible(false);
                CalculatorFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_paintButtActionPerformed

    private void stopButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtActionPerformed
        // TODO add your handling code here:
        StopFrame stp = new StopFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                stp.setVisible(true);
                CalculatorFrame.this.setVisible(false);
                CalculatorFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_stopButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorFrame().setVisible(true);
            }
        });
    }
    
    public void close(){
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CalculatorFrame.this.setVisible(false);
            }
    });
 }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alarmButt;
    private javax.swing.JButton calcButt;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelDate1;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jLabelTime1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton musicButt;
    private javax.swing.JButton paintButt;
    private javax.swing.JButton stopButt;
    private javax.swing.JButton textButt;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowOpened(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowClosing(WindowEvent e) {
    Main main = new Main();
               java.awt.EventQueue.invokeLater(new Runnable() {
                   public void run() {
                       main.setVisible(true);
                       CalculatorFrame.this.dispose();
                   }
               });
    }

    @Override
    public void windowClosed(WindowEvent e) {
        Main main = new Main();
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    main.setVisible(true);
                    CalculatorFrame.this.dispose();
                }
            });
    }

    @Override
    public void windowIconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowActivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    private void clock() {
        try{
            Timer timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Calendar cal1 = new GregorianCalendar();
                    Calendar cal2 = cal1.getInstance();
                    
                    String date = new SimpleDateFormat("MMMM '-' dd '-' YYYY EEEE").format(Calendar.getInstance().getTime()).toUpperCase();
                    String time = new SimpleDateFormat("hh ':' mm ':' ss").format(Calendar.getInstance().getTime());
                    
                    String am_pm;
                    if (cal1.get(Calendar.AM_PM) == 0){
                        am_pm = "AM";
                    } else{
                        am_pm = "PM";
                    }
                    jLabelDate.setText(date);
                    jLabelTime.setText(time+" "+ am_pm);
                }

               
            });
            timer.start();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
}
