
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Charles Ian
 */
public class Main extends javax.swing.JFrame {
    
    public static int counter = 0;
    public String filePath = "";
    CalculatorFrame cal = new CalculatorFrame();
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        clock();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        musicButt = new javax.swing.JButton();
        calcButt = new javax.swing.JButton();
        textButt = new javax.swing.JButton();
        alarmButt = new javax.swing.JButton();
        paintButt = new javax.swing.JButton();
        stopButt = new javax.swing.JButton();
        jLabelTime = new javax.swing.JLabel();
        jLabelDate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuExit = new javax.swing.JMenu();
        jMenuAboutUs = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cardinal OS Group 6");
        setMinimumSize(new java.awt.Dimension(1095, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(1080, 720));
        jPanel1.setLayout(null);

        musicButt.setOpaque(false);
        musicButt.setContentAreaFilled(false);
        musicButt.setBorderPainted(false);
        musicButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Music Player_LM.png"))); // NOI18N
        musicButt.setMaximumSize(new java.awt.Dimension(140, 80));
        musicButt.setPreferredSize(new java.awt.Dimension(140, 80));
        musicButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicButtActionPerformed(evt);
            }
        });
        jPanel1.add(musicButt);
        musicButt.setBounds(30, 250, 100, 90);

        calcButt.setOpaque(false);
        calcButt.setContentAreaFilled(false);
        calcButt.setBorderPainted(false);
        calcButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Calculator_LM.png"))); // NOI18N
        calcButt.setMaximumSize(new java.awt.Dimension(140, 80));
        calcButt.setPreferredSize(new java.awt.Dimension(140, 80));
        calcButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtActionPerformed(evt);
            }
        });
        jPanel1.add(calcButt);
        calcButt.setBounds(30, 30, 110, 80);

        textButt.setOpaque(false);
        textButt.setContentAreaFilled(false);
        textButt.setBorderPainted(false);
        textButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Text Editor_LM.png"))); // NOI18N
        textButt.setText("jButton2");
        textButt.setMaximumSize(new java.awt.Dimension(140, 80));
        textButt.setPreferredSize(new java.awt.Dimension(140, 80));
        textButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textButtActionPerformed(evt);
            }
        });
        jPanel1.add(textButt);
        textButt.setBounds(30, 140, 110, 80);

        alarmButt.setOpaque(false);
        alarmButt.setContentAreaFilled(false);
        alarmButt.setBorderPainted(false);
        alarmButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Alarm_LM.png"))); // NOI18N
        alarmButt.setMaximumSize(new java.awt.Dimension(140, 80));
        alarmButt.setPreferredSize(new java.awt.Dimension(140, 80));
        alarmButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarmButtActionPerformed(evt);
            }
        });
        jPanel1.add(alarmButt);
        alarmButt.setBounds(10, 370, 140, 80);

        paintButt.setOpaque(false);
        paintButt.setContentAreaFilled(false);
        paintButt.setBorderPainted(false);
        paintButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Paint_LM.png"))); // NOI18N
        paintButt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        paintButt.setMaximumSize(new java.awt.Dimension(140, 80));
        paintButt.setMinimumSize(new java.awt.Dimension(140, 80));
        paintButt.setPreferredSize(new java.awt.Dimension(140, 80));
        paintButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintButtActionPerformed(evt);
            }
        });
        jPanel1.add(paintButt);
        paintButt.setBounds(10, 490, 140, 80);

        stopButt.setOpaque(false);
        stopButt.setContentAreaFilled(false);
        stopButt.setBorderPainted(false);
        stopButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Stopwatch_LM.png"))); // NOI18N
        stopButt.setMaximumSize(new java.awt.Dimension(140, 80));
        stopButt.setMinimumSize(new java.awt.Dimension(140, 80));
        stopButt.setPreferredSize(new java.awt.Dimension(140, 80));
        stopButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtActionPerformed(evt);
            }
        });
        jPanel1.add(stopButt);
        stopButt.setBounds(10, 610, 140, 80);
        jPanel1.add(jLabelTime);
        jLabelTime.setBounds(700, 80, 290, 40);
        jPanel1.add(jLabelDate);
        jLabelDate.setBounds(700, 30, 280, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/Home_LM.png"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -10, 1080, 730);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1070, 713);

        jMenuExit.setText("Exit");
        jMenuExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuExitMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuExit);

        jMenuAboutUs.setText("About Us");
        jMenuAboutUs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAboutUsMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAboutUs);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musicButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicButtActionPerformed
        // TODO add your handling code here:
        MusicFrame ms = new MusicFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ms.setVisible(true);
                Main.this.setVisible(false);
                Main.this.dispose();
            }
        });
        
        /*Login Log = new Login();
        sc.setVisible(false);
        Log.setVisible(true);
        
        //close load screen
        sc.dispose();*/
    }//GEN-LAST:event_musicButtActionPerformed

    private void calcButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtActionPerformed
        // TODO add your handling code here:
 
        
        CalculatorFrame cal = new CalculatorFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cal.setVisible(true);
                Main.this.setVisible(false);
                Main.this.dispose();
            }
        });
        
    }//GEN-LAST:event_calcButtActionPerformed

    private void alarmButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarmButtActionPerformed
        // TODO add your handling code here:
                Alarm al = new Alarm();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                al.setVisible(true);
                Main.this.setVisible(false);
                Main.this.dispose();
            }
        });
    }//GEN-LAST:event_alarmButtActionPerformed

    private void paintButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintButtActionPerformed
        // TODO add your handling code here:
                
        PaintFrame paint = new PaintFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                paint.setVisible(true);
                Main.this.setVisible(false);
                Main.this.dispose();
            }
        });
        
    }//GEN-LAST:event_paintButtActionPerformed

    private void stopButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtActionPerformed
        // TODO add your handling code here:
        StopFrame sw = new StopFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sw.setVisible(true);
                Main.this.setVisible(false);
                Main.this.dispose();
            }
        });
    }//GEN-LAST:event_stopButtActionPerformed

    private void textButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textButtActionPerformed
        // TODO add your handling code here:
        textEditorFrame te = new textEditorFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                te.setVisible(true);
                Main.this.setVisible(false);
                Main.this.dispose();
            }
        });
    }//GEN-LAST:event_textButtActionPerformed

    private void jMenuExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuExitMouseClicked

    private void jMenuAboutUsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAboutUsMouseClicked
        // TODO add your handling code here:
                JFrame aboutUs = new JFrame("About Us");      
        JOptionPane.showMessageDialog(aboutUs, "This is a project by Group 6 of BM5 CS128-8L: "
                + "\nCharles Ian Monteloyola"
                + "\nKarina Francesca Soo"
                + "\nPatrick Miguel Purificacion"
                + "\nJeremey Joshua Yao"
                + "\nJenoel Kline Recena");
    }//GEN-LAST:event_jMenuAboutUsMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alarmButt;
    private javax.swing.JButton calcButt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JMenu jMenuAboutUs;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuExit;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JButton musicButt;
    private javax.swing.JButton paintButt;
    private javax.swing.JButton stopButt;
    private javax.swing.JButton textButt;
    // End of variables declaration//GEN-END:variables

    private void clock() {
        try{
            Timer timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Calendar cal1 = new GregorianCalendar();
                    Calendar cal2 = cal1.getInstance();
                    
                    String date = new SimpleDateFormat("MMMM '-' dd '-' YYYY EEEE").format(Calendar.getInstance().getTime()).toUpperCase();
                    String time = new SimpleDateFormat("hh ':' mm ':' ss").format(Calendar.getInstance().getTime());
                    
                    String am_pm;
                    if (cal1.get(Calendar.AM_PM) == 0){
                        am_pm = "AM";
                    } else{
                        am_pm = "PM";
                    }
                    jLabelDate.setText(date);
                    jLabelTime.setText(time+" "+ am_pm);
                }

               
            });
            timer.start();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
  }
