/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/**
 *
 * @author jerem
 */
public class StopwatchPanel extends javax.swing.JPanel {

    static int hours = 0;
    static int minutes = 0;
    static int seconds = 0;
    static int miliseconds = 0;
    static boolean state = true;
    /**
     * Creates new form Stopwatch
     */
    public StopwatchPanel() {
        initComponents();
    }
    
    private void turnoff(){

    }
    
    public void clock(){
        try{
            Timer timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Calendar cal1 = new GregorianCalendar();
                    Calendar cal2 = cal1.getInstance();
                    
                    String date = new SimpleDateFormat("MMMM '-' dd '-' YYYY EEEE").format(Calendar.getInstance().getTime()).toUpperCase();
                    String time = new SimpleDateFormat("hh ':' mm ':' ss").format(Calendar.getInstance().getTime());
                    
                    String am_pm;
                    if (cal1.get(Calendar.AM_PM) == 0){
                        am_pm = "AM";
                    } else{
                        am_pm = "PM";
                    }
                    jLabelDate1.setText(date);
                    jLabelTime.setText(time+" "+ am_pm);
                }
            });
            timer.start();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelDate1 = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bstop = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        bstart = new javax.swing.JButton();
        blap = new javax.swing.JButton();
        blap2 = new javax.swing.JButton();
        blap3 = new javax.swing.JButton();
        jlap = new javax.swing.JLabel();
        jlap2 = new javax.swing.JLabel();
        jlap3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelDate1.setFont(new java.awt.Font("SimHei", 0, 18)); // NOI18N
        jLabelDate1.setForeground(new java.awt.Color(51, 51, 255));
        jLabelDate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDate1.setText("DATE");
        add(jLabelDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 370, 60));

        jLabelTime.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTime.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTime.setText("TIME");
        add(jLabelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 380, 61));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 56)); // NOI18N
        jLabel1.setText("STOPWATCH");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 370, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("00:00:00:000");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 340, 50));

        bstop.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bstop.setText("STOP");
        bstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstopActionPerformed(evt);
            }
        });
        add(bstop, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 130, 40));

        breset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        breset.setText("RESET");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });
        add(breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 130, 40));

        bstart.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bstart.setText("START");
        bstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstartActionPerformed(evt);
            }
        });
        add(bstart, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 130, 40));

        blap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        blap.setText("LAP");
        blap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blapActionPerformed(evt);
            }
        });
        add(blap, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 140, 50));

        blap2.setText("LAP");
        blap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blap2ActionPerformed(evt);
            }
        });
        add(blap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 140, 50));

        blap3.setText("LAP");
        blap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blap3ActionPerformed(evt);
            }
        });
        add(blap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 140, 50));

        jlap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlap.setText("00:00:00:000");
        add(jlap, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 150, 50));

        jlap2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlap2.setText("00:00:00:000");
        add(jlap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 150, 50));

        jlap3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlap3.setText("00:00:00:000");
        add(jlap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, 150, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/JPanels/Stopwatch.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setPreferredSize(new java.awt.Dimension(1080, 720));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 740));
    }// </editor-fold>//GEN-END:initComponents

    private void bstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstartActionPerformed
        blap.setVisible(true);
		state = true;
	Thread time = new Thread(){
		public void run(){
			
			for(;;){
			 if (state==true){
			try{
				sleep(1);
				if(miliseconds>=1000){
					miliseconds = 0;
					seconds ++;
				}
				if (seconds>=60){
					seconds=0;
					minutes++;
				}
				if (minutes>=60){
					minutes = 0;
					hours++;
				}
				miliseconds++;
				jLabel1.setText(hours+":"+ minutes+":"+seconds+":"+miliseconds);
			} catch(Exception e) {
			}
		}
			else{
				break;
					}
		}
	}
};
time.start();
    }//GEN-LAST:event_bstartActionPerformed

    private void bstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstopActionPerformed
        state=false;
    }//GEN-LAST:event_bstopActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        state = false;
        jlap.setText("00:00:00:000");
        hours = 0;
        minutes = 0;
        seconds = 0;
        miliseconds = 0;
        jlap2.setText("00:00:00:000");
        jlap3.setText("00:00:00:000");
        blap.setVisible(false);
        blap2.setVisible(false);
        jlap2.setVisible(false);
        jlap3.setVisible(false);
        blap.setEnabled(true);
        blap2.setEnabled(true);
    }//GEN-LAST:event_bresetActionPerformed

    private void blapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blapActionPerformed
        jlap.setVisible(true);
        jlap.setText(jLabel2.getText());
        blap.setEnabled(false);
        blap2.setVisible(true);
    }//GEN-LAST:event_blapActionPerformed

    private void blap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blap2ActionPerformed
        jlap2.setText(jLabel2.getText());
        blap2.setEnabled(false);
    }//GEN-LAST:event_blap2ActionPerformed

    private void blap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blap3ActionPerformed
        jlap3.setText(jLabel2.getText());
        blap3.setEnabled(false);
    }//GEN-LAST:event_blap3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blap;
    private javax.swing.JButton blap2;
    private javax.swing.JButton blap3;
    private javax.swing.JButton breset;
    private javax.swing.JButton bstart;
    private javax.swing.JButton bstop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDate1;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jlap;
    private javax.swing.JLabel jlap2;
    private javax.swing.JLabel jlap3;
    // End of variables declaration//GEN-END:variables
}

