
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.Timer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Charles Ian
 */
public class StopFrame extends javax.swing.JFrame {

    static int hours = 0;
    static int minutes = 0;
    static int seconds = 0;
    static int miliseconds = 0;
    static boolean state = true;
    /**
     * Creates new form StopFrame
     */
    public StopFrame() {
        initComponents();
        clock();
        jlap.setVisible(false);
        jlap2.setVisible(false);
        jlap3.setVisible(false);
        blap.setVisible(false);
        blap2.setVisible(false);
        blap3.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        bstop = new javax.swing.JButton();
        breset = new javax.swing.JButton();
        bstart = new javax.swing.JButton();
        jlap = new javax.swing.JLabel();
        jlap2 = new javax.swing.JLabel();
        jlap3 = new javax.swing.JLabel();
        blap3 = new javax.swing.JButton();
        blap2 = new javax.swing.JButton();
        blap = new javax.swing.JButton();
        calcButt = new javax.swing.JButton();
        textButt = new javax.swing.JButton();
        musicButt = new javax.swing.JButton();
        alarmButt = new javax.swing.JButton();
        paintButt = new javax.swing.JButton();
        stopButt = new javax.swing.JButton();
        jLabelDate = new javax.swing.JLabel();
        jLabelTime = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cardinal OS Group 6");
        setMinimumSize(new java.awt.Dimension(1095, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("00:00:00:000");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 250, 340, 50));

        bstop.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bstop.setText("STOP");
        bstop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstopActionPerformed(evt);
            }
        });
        getContentPane().add(bstop, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 130, 40));

        breset.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        breset.setText("RESET");
        breset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bresetActionPerformed(evt);
            }
        });
        getContentPane().add(breset, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 360, 130, 40));

        bstart.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        bstart.setText("START");
        bstart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bstartActionPerformed(evt);
            }
        });
        getContentPane().add(bstart, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 130, 40));

        jlap.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlap.setText("00:00:00:000");
        getContentPane().add(jlap, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 460, 150, 50));

        jlap2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlap2.setText("00:00:00:000");
        getContentPane().add(jlap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 530, 150, 50));

        jlap3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlap3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlap3.setText("00:00:00:000");
        getContentPane().add(jlap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 590, 150, 50));

        blap3.setText("LAP");
        blap3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blap3ActionPerformed(evt);
            }
        });
        getContentPane().add(blap3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 590, 140, 50));

        blap2.setText("LAP");
        blap2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blap2ActionPerformed(evt);
            }
        });
        getContentPane().add(blap2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 530, 140, 50));

        blap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        blap.setText("LAP");
        blap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blapActionPerformed(evt);
            }
        });
        getContentPane().add(blap, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 460, 140, 50));

        calcButt.setOpaque(false);
        calcButt.setContentAreaFilled(false);
        calcButt.setBorderPainted(false);
        calcButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Calculator_LM.png"))); // NOI18N
        calcButt.setMaximumSize(new java.awt.Dimension(140, 80));
        calcButt.setPreferredSize(new java.awt.Dimension(140, 80));
        calcButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtActionPerformed(evt);
            }
        });
        getContentPane().add(calcButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 110, 80));

        textButt.setOpaque(false);
        textButt.setContentAreaFilled(false);
        textButt.setBorderPainted(false);
        textButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Text Editor_LM.png"))); // NOI18N
        textButt.setText("jButton2");
        textButt.setMaximumSize(new java.awt.Dimension(140, 80));
        textButt.setPreferredSize(new java.awt.Dimension(140, 80));
        textButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textButtActionPerformed(evt);
            }
        });
        getContentPane().add(textButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        musicButt.setOpaque(false);
        musicButt.setContentAreaFilled(false);
        musicButt.setBorderPainted(false);
        musicButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Music Player_LM.png"))); // NOI18N
        musicButt.setMaximumSize(new java.awt.Dimension(140, 80));
        musicButt.setPreferredSize(new java.awt.Dimension(140, 80));
        musicButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musicButtActionPerformed(evt);
            }
        });
        getContentPane().add(musicButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 90));

        alarmButt.setOpaque(false);
        alarmButt.setContentAreaFilled(false);
        alarmButt.setBorderPainted(false);
        alarmButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Alarm_LM.png"))); // NOI18N
        alarmButt.setMaximumSize(new java.awt.Dimension(140, 80));
        alarmButt.setPreferredSize(new java.awt.Dimension(140, 80));
        alarmButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alarmButtActionPerformed(evt);
            }
        });
        getContentPane().add(alarmButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        paintButt.setOpaque(false);
        paintButt.setContentAreaFilled(false);
        paintButt.setBorderPainted(false);
        paintButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Paint_LM.png"))); // NOI18N
        paintButt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        paintButt.setMaximumSize(new java.awt.Dimension(140, 80));
        paintButt.setMinimumSize(new java.awt.Dimension(140, 80));
        paintButt.setPreferredSize(new java.awt.Dimension(140, 80));
        paintButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paintButtActionPerformed(evt);
            }
        });
        getContentPane().add(paintButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        stopButt.setOpaque(false);
        stopButt.setContentAreaFilled(false);
        stopButt.setBorderPainted(false);
        stopButt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/Stopwatch_LM.png"))); // NOI18N
        stopButt.setMaximumSize(new java.awt.Dimension(140, 80));
        stopButt.setMinimumSize(new java.awt.Dimension(140, 80));
        stopButt.setPreferredSize(new java.awt.Dimension(140, 80));
        stopButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtActionPerformed(evt);
            }
        });
        getContentPane().add(stopButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, -1, -1));
        getContentPane().add(jLabelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 30, 280, 40));
        getContentPane().add(jLabelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 80, 290, 40));

        home.setOpaque(false);
        home.setContentAreaFilled(false);
        home.setBorderPainted(false);
        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Buttons/HomeButton_LM.png"))); // NOI18N
        home.setText("home");
        home.setMaximumSize(new java.awt.Dimension(140, 80));
        home.setPreferredSize(new java.awt.Dimension(140, 80));
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Frames/Stopwatch_LM.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bstopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstopActionPerformed
        state=false;
    }//GEN-LAST:event_bstopActionPerformed

    private void bresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bresetActionPerformed
        state = false;
        hours = 0;
        minutes = 0;
        seconds = 0;
        miliseconds = 0;
        jlap.setText("00:00:00:000");
        jlap2.setText("00:00:00:000");
        jlap3.setText("00:00:00:000");
        jlap.setVisible(false);
        jlap2.setVisible(false);
        jlap3.setVisible(false);
        blap.setVisible(false);
        blap2.setVisible(false);
        blap3.setVisible(false);
        blap.setEnabled(true);
        jLabel3.setText("00:00:00:000");
        
    }//GEN-LAST:event_bresetActionPerformed

    private void bstartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bstartActionPerformed
        jlap.setVisible(true);
        blap.setVisible(true);
        state = true;
        Thread time = new Thread(){
            public void run(){

                for(;;){
                    if (state==true){
                        try{
                            sleep(1);
                            if(miliseconds>=1000){
                                miliseconds = 0;
                                seconds ++;
                            }
                            if (seconds>=60){
                                seconds=0;
                                minutes++;
                            }
                            if (minutes>=60){
                                minutes = 0;
                                hours++;
                            }
                            miliseconds++;
                            jLabel3.setText(String.format("%02d:%02d:%02d:%02d", hours, minutes, seconds, miliseconds));
                            
                        } catch(Exception e) {
                        }
                    }
                    else{
                        break;
                    }
                }
            }
        };
        time.start();
    }//GEN-LAST:event_bstartActionPerformed

    private void blap3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blap3ActionPerformed
        jlap3.setText(jLabel3.getText());
        blap3.setEnabled(false);
        
        

        
    }//GEN-LAST:event_blap3ActionPerformed

    private void blap2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blap2ActionPerformed
        jlap2.setText(jLabel3.getText());
        blap2.setEnabled(false);
        blap.setVisible(true);
        blap3.setVisible(true);
        jlap3.setVisible(true);

        
    }//GEN-LAST:event_blap2ActionPerformed

    private void blapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blapActionPerformed
        blap.setEnabled(false);
        jlap2.setVisible(true);
        blap2.setVisible(true);
        jlap.setText(jLabel3.getText());
        

    }//GEN-LAST:event_blapActionPerformed

    private void musicButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musicButtActionPerformed
        // TODO add your handling code here:
        MusicFrame ms = new MusicFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ms.setVisible(true);
                StopFrame.this.setVisible(false);
                StopFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_musicButtActionPerformed

    private void stopButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtActionPerformed
        // TODO add your handling code here:
        StopFrame stp = new StopFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                stp.setVisible(true);
                StopFrame.this.setVisible(false);
                StopFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_stopButtActionPerformed

    private void calcButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtActionPerformed
        // TODO add your handling code here:
        CalculatorFrame cal = new CalculatorFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                cal.setVisible(true);
                StopFrame.this.setVisible(false);
                StopFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_calcButtActionPerformed

    private void textButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textButtActionPerformed
        // TODO add your handling code here:
        textEditorFrame txtEd = new textEditorFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                txtEd.setVisible(true);
                StopFrame.this.setVisible(false);
                StopFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_textButtActionPerformed

    private void alarmButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alarmButtActionPerformed
        // TODO add your handling code here:
        Alarm alrm = new Alarm();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                alrm.setVisible(true);
                StopFrame.this.setVisible(false);
                StopFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_alarmButtActionPerformed
private void clock() {
        try{
            Timer timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    Calendar cal1 = new GregorianCalendar();
                    Calendar cal2 = cal1.getInstance();
                    
                    String date = new SimpleDateFormat("MMMM '-' dd '-' YYYY EEEE").format(Calendar.getInstance().getTime()).toUpperCase();
                    String time = new SimpleDateFormat("hh ':' mm ':' ss").format(Calendar.getInstance().getTime());
                    
                    String am_pm;
                    if (cal1.get(Calendar.AM_PM) == 0){
                        am_pm = "AM";
                    } else{
                        am_pm = "PM";
                    }
                    jLabelDate.setText(date);
                    jLabelTime.setText(time+" "+ am_pm);
                }

               
            });
            timer.start();
        } catch(Exception e){
            e.printStackTrace();
        }
    }
    private void paintButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paintButtActionPerformed
        // TODO add your handling code here:
        PaintFrame pnt = new PaintFrame();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                pnt.setVisible(true);
                StopFrame.this.setVisible(false);
                StopFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_paintButtActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        Main main = new Main();
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                main.setVisible(true);
                StopFrame.this.setVisible(false);
                StopFrame.this.dispose();
            }
        });
    }//GEN-LAST:event_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StopFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StopFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alarmButt;
    private javax.swing.JButton blap;
    private javax.swing.JButton blap2;
    private javax.swing.JButton blap3;
    private javax.swing.JButton breset;
    private javax.swing.JButton bstart;
    private javax.swing.JButton bstop;
    private javax.swing.JButton calcButt;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelDate;
    private javax.swing.JLabel jLabelTime;
    private javax.swing.JLabel jlap;
    private javax.swing.JLabel jlap2;
    private javax.swing.JLabel jlap3;
    private javax.swing.JButton musicButt;
    private javax.swing.JButton paintButt;
    private javax.swing.JButton stopButt;
    private javax.swing.JButton textButt;
    // End of variables declaration//GEN-END:variables
}
